### ISSUE TITLE
Great!  How about the train/infer time?

### ISSUE THREAD

**Issue by yuedajiong** [AntonioTepsich/Convolutional-KANs#2]
as title

and if we want better precision against to big conv, how about the parameters increasing?

> KKAN means CKAN,...,CKAN,...,KAN,...
> CKAN+MLP means CKAN,...,CKAN,...,MLP,...
> right?

thanks!

**Comment by XiangboGaoBarry** [comment]
Hi, here I implement ConvKAN with different activation formulations. https://github.com/XiangboGaoBarry/ConvKAN-Zoo

**Comment by yuedajiong** [comment]
@XiangboGaoBarry   
Greaaaaaaaaaaaaaaaaaaaaaaaaaaaat!

看到了，牛逼，细致。  已经下载了在看。  （刚看到了一个repo:  https://github.com/[cloneofsimo/imagenet.int8 )我想从最最最原始的一步开始，走到我git主页搞的那个3d task)

除了祝你发大财，好像其他的赞美都不够!!!!!!!!!!!!!!!!!
