### ISSUE TITLE
Cifar10

### ISSUE THREAD

**Issue by ernleite** [AntonioTepsich/Convolutional-KANs#3]
Hi team, 
Why not trying convolution with CIFAR10 (instead of MNIST).
I think it would be a better option as this dataset contains more contextual information? 
I saw already some KAN implementation on it

Also I am working on model parallelism. I was wondering if I can work on that. But I am not familiar with KAN so I need to learn how the feed forward and backpropagation work to see how we can parallelize a KAN
Happy to chat with the team
thanks!

**Comment by AlexBodner** [comment]
Hey! Would be amazing if you make the parellel processing work! We are already trying on Cifar 10, but the inefficiency of current methods makes it difficult. You can write me at my email or twitter that are on the README and lets have a chat!
Regards,
Alex
