### ISSUE TITLE
How to set the bias

### ISSUE THREAD

**Issue by entuo** [AntonioTepsich/Convolutional-KANs#5]
Congratulations, this is groundbreaking work.
I was wondering if it could be used as a replacement for nn.conv2d and I realized that there is no bias attribute in it, how should I set it up, thanks for your answer!

**Comment by AlexBodner** [comment]
Hi! In a KAN that uses B Splines you dont need a bias! It is different than a normal network, as you learn an activation function that includes in its representation a potential bias that it might need.
