### ISSUE TITLE
Questions about convolution operation

### ISSUE THREAD

**Issue by zhongwlf** [AntonioTepsich/Convolutional-KANs#9]
In fig1, the output from conv2 is 5*5, but the input to KANLinear is 245; in fig2 and fig3, after passing through KANconv, the input to nn.linear is 625. Could you please explain why this is the case? Thank you very much!

![q1](https://github.com/AntonioTepsich/Convolutional-KANs/assets/100411728/6c3bc374-0dbd-4e18-9ea4-dc7197765faf)
![q2](https://github.com/AntonioTepsich/Convolutional-KANs/assets/100411728/46e32271-8afe-4456-87a2-a640f3a14f94)
![q3](https://github.com/AntonioTepsich/Convolutional-KANs/assets/100411728/d2d5031d-67b1-477f-90b9-60c041c00dbf)

**Comment by AlexBodner** [comment]
Because our convolutons follow other convention. Our convolutions receive the number of filters and each filter is applied to each chanell i.e., if you receive a (3,24,24) image and pass n_convs = 5 with padding, you get a (15,24,24) output

**Comment by zhongwlf** [comment]
Thank you for your explanation and your KAN-CNN work, which has benefited me greatly！So cool！
